apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name | default (printf "%s-service" .Values.api.name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.api.name }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
  type: {{ .Values.api.service.type }}
